---
- name: "Update"
  become: yes
  apt:
    update_cache: yes
    cache_valid_time: 86400

- name: "delete outdated dependencies"
  become: yes
  apt:
    autoremove: yes

- name: "upgrade packages"
  become: yes
  apt:
    upgrade: yes

- name: install deps
  become: yes
  apt:
    name: ["nodejs", "npm"]
    state: latest
    update_cache: yes

- name: install pm2
  become: yes
  npm:
    name: pm2
    global: yes
    state: latest
    production: yes

- name: "Unarchive build artifact"
  become: yes
  unarchive:
    src: "files/build-artifact.tar.gz"
    dest: .

- name: "Start application"
  become: yes
  shell: |
    npm install
    pm2 stop default
    pm2 start npm -- start
